version: '3.1' # docker version

services:
  web:
    image: php:apache
    build: .
    ports:
      - "80:80"
      - "443:443" # ssl traffic
    volumes:
      - .:/var/www/html # sync project dir with container web dir
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: form_creator
      MYSQL_USER: user
      MYSQL_PASSWORD: password 
    volumes:
      - db_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

volumes:
  db_data:
